import Head from 'next/head'
import AdminCMS from '../../cms'

export default function Admin({ data }) {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminCMS />
    </>
  )
}