import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { db } from '../config/firebase'
import { collection, getDocs } from "firebase/firestore";


export default function Home({ blogs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CMS com Firebase</h1>
        
        <Link href="/admin">
          <a style={{ display: 'block', border: '1px solid #ccc', padding: '10px', margin: '10px 0' }}>
            <h2>Admin</h2>
          </a>
        </Link>

      <h2>Blogs info</h2>
      <pre>
        {JSON.stringify(blogs, null, 2)}
      </pre>   
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const querySnapshot = await getDocs(collection(db, "blog"));
  const blogs = querySnapshot?.docs?.map(doc => doc.data());

  return {
    props: {
      blogs
    }
  }
}
